# Generated by Django 5.0.6 on 2024-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_game_année_de_sortie_game_développeur_game_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plateform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='plateforme',
            field=models.ManyToManyField(to='listings.plateform'),
        ),
    ]
