# Generated by Django 5.0.6 on 2024-05-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_plateform_game_plateforme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='année_de_sortie',
            new_name='annee_de_sortie',
        ),
    ]
