# Generated by Django 5.0.6 on 2024-05-29 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_année_de_sortie_game_annee_de_sortie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='développeur',
            new_name='developpeur',
        ),
    ]
